"""Built-in themes for p2pchat.

Color palettes adapted from Posting by Darren Burns:
https://github.com/darrenburns/posting
"""

from textual.theme import Theme as TextualTheme

BUILTIN_THEMES: dict[str, TextualTheme] = {
    "galaxy": TextualTheme(
        name="galaxy",
        primary="#C45AFF",
        secondary="#a684e8",
        warning="#FFD700",
        error="#FF4500",
        success="#00FA9A",
        accent="#FF69B4",
        background="#0F0F1F",
        surface="#1E1E3F",
        panel="#2D2B55",
        dark=True,
        variables={
            "input-cursor-background": "#C45AFF",
            "footer-background": "transparent",
        },
    ),
    "nebula": TextualTheme(
        name="nebula",
        primary="#4A9CFF",
        secondary="#66D9EF",
        warning="#FFB454",
        error="#FF5555",
        success="#50FA7B",
        accent="#FF79C6",
        surface="#193549",
        panel="#1F4662",
        background="#0D2137",
        dark=True,
        variables={
            "input-selection-background": "#4A9CFF 35%",
        },
    ),
    "sunset": TextualTheme(
        name="sunset",
        primary="#FF7E5F",
        secondary="#FEB47B",
        warning="#FFD93D",
        error="#FF5757",
        success="#98D8AA",
        accent="#B983FF",
        background="#2B2139",
        surface="#362C47",
        panel="#413555",
        dark=True,
        variables={
            "input-cursor-background": "#FF7E5F",
            "input-selection-background": "#FF7E5F 35%",
            "footer-background": "transparent",
            "button-color-foreground": "#2B2139",
        },
    ),
    "aurora": TextualTheme(
        name="aurora",
        primary="#45FFB3",
        secondary="#A1FCDF",
        accent="#DF7BFF",
        warning="#FFE156",
        error="#FF6B6B",
        success="#64FFDA",
        background="#0A1A2F",
        surface="#142942",
        panel="#1E3655",
        dark=True,
        variables={
            "input-cursor-background": "#45FFB3",
            "input-selection-background": "#45FFB3 35%",
            "footer-background": "transparent",
            "button-color-foreground": "#0A1A2F",
        },
    ),
    "nautilus": TextualTheme(
        name="nautilus",
        primary="#0077BE",
        secondary="#20B2AA",
        warning="#FFD700",
        error="#FF6347",
        success="#32CD32",
        accent="#FF8C00",
        background="#001F3F",
        surface="#003366",
        panel="#005A8C",
        dark=True,
    ),
    "cobalt": TextualTheme(
        name="cobalt",
        primary="#334D5C",
        secondary="#66B2FF",
        warning="#FFAA22",
        error="#E63946",
        success="#4CAF50",
        accent="#D94E64",
        surface="#27343B",
        panel="#2D3E46",
        background="#1F262A",
        dark=True,
        variables={
            "input-selection-background": "#4A9CFF 35%",
        },
    ),
    "twilight": TextualTheme(
        name="twilight",
        primary="#367588",
        secondary="#5F9EA0",
        warning="#FFD700",
        error="#FF6347",
        success="#00FA9A",
        accent="#FF7F50",
        background="#191970",
        surface="#3B3B6D",
        panel="#4C516D",
        dark=True,
    ),
    "hacker": TextualTheme(
        name="hacker",
        primary="#00FF00",
        secondary="#3A9F3A",
        warning="#00FF66",
        error="#FF0000",
        success="#00DD00",
        accent="#00FF33",
        background="#000000",
        surface="#0A0A0A",
        panel="#111111",
        dark=True,
    ),
    "manuscript": TextualTheme(
        name="manuscript",
        primary="#2C4251",
        secondary="#6B4423",
        accent="#8B4513",
        warning="#B4846C",
        error="#A94442",
        success="#2D5A27",
        background="#F5F1E9",
        surface="#EBE6D9",
        panel="#E0DAC8",
        dark=False,
        variables={
            "input-cursor-background": "#2C4251",
            "input-selection-background": "#2C4251 25%",
            "footer-background": "#2C4251",
            "footer-key-foreground": "#F5F1E9",
            "footer-description-foreground": "#F5F1E9",
            "button-color-foreground": "#F5F1E9",
        },
    ),
    "hypernova": TextualTheme(
        name="hypernova",
        primary="#00F5D4",
        secondary="#7B2FF7",
        warning="#FEE440",
        error="#F72585",
        success="#80FF72",
        accent="#4CC9F0",
        background="#0B0B12",
        surface="#121225",
        panel="#1A1A32",
        dark=True,
        variables={
            "input-cursor-background": "#4CC9F0",
            "input-selection-background": "#4CC9F0 30%",
            "footer-background": "transparent",
            "button-color-foreground": "#0B0B12",
        },
    ),
    "synthwave": TextualTheme(
        name="synthwave",
        primary="#FF006E",
        secondary="#8338EC",
        warning="#FFBE0B",
        error="#FB5607",
        success="#06FFA5",
        accent="#3A86FF",
        background="#0F0A19",
        surface="#1A0F26",
        panel="#251833",
        dark=True,
        variables={
            "input-cursor-background": "#FF006E",
            "input-selection-background": "#FF006E 25%",
            "footer-background": "transparent",
            "button-color-foreground": "#0F0A19",
        },
    ),
}
